# ingress-main.yaml (principal, apunta a la API de Python)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-main
  namespace: so1-fase2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-python-service
                port:
                  number: 80
---
# ingress-canary.yaml (canary, reparte tráfico a API de Node.js)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-canary
  namespace: so1-fase2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"  # Cambia a 30 para 30%, etc.
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-rest-service
                port:
                  number: 80
