version: '3.9'

services:

  monitor:
    image: josmalopez/monitor:1.1       # Usamos  directamente la imagen local ya creada

  api_python:
      image: josmalopez/api_python:1.1
      restart: always
      ports:
        - "3001:3001"
      depends_on:
        - monitor

  api_rest:
      image: josmalopez/api_rest:1.1
      restart: always
      ports:
        - "3002:3002"
      depends_on:
        - monitor

  socket:
      image: josmalopez/socket:1.0
      restart: always
      ports:
        - "4000:4000"
      depends_on:
        - api_rest
        - api_python

  frontend:
      image: josmalopez/frontend:1.1
      restart: always
      ports:
        - "3000:3000"
      depends_on:
        - socket
  

